# Generated by Django 4.2.2 on 2023-07-22 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_data_migration"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="courses",
            managers=[],
        ),
    ]
